**Perceptron Algorithm**
 

 Creating Perceptron Algorithm

In [2]:
import numpy as np
class PerceptronAlgorithm:
    def __init__(self, learning_rate=0.01, iterations=100):

        self.lr = learning_rate
        self.n = iterations
        self.weights = None
        self.bias = None

    def fit(self, X, Y):
        self.weights = np.zeros(X.shape[1])
        self.bias = 0
        for epoch in range(self.n):
            for i in range(X.shape[0]):
                Y_pred = np.dot(self.weights, X[i]) + self.bias
                self.weights = self.weights + self.lr * (Y[i] - Y_pred) * X[i]
                self.bias = self.bias + self.lr * (Y[i] - Y_pred)

    def predict(self, X):
        y_pred = []
        for i in range(X.shape[0]):
            y_pred.append(self.helper(np.dot(self.weights, X[i]) + self.bias))
        return y_pred

    def helper(self, helper):
        if (helper >= 0):
            return 1
        return 0

Testing Algorithm

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [29]:
df = pd.read_csv('bank-full.csv')
df.head()


age           job  marital  education  ... pdays  previous poutcome   y
0   58    management  married   tertiary  ...    -1         0  unknown  no
1   44    technician   single  secondary  ...    -1         0  unknown  no
2   33  entrepreneur  married  secondary  ...    -1         0  unknown  no
3   47   blue-collar  married    unknown  ...    -1         0  unknown  no
4   33       unknown   single    unknown  ...    -1         0  unknown  no

[5 rows x 17 columns]

In [31]:
x = df.iloc[:, 0:-1]
y = df.iloc[:, -1:]
x

age           job   marital  ... pdays previous  poutcome
0       58    management   married  ...    -1        0   unknown
1       44    technician    single  ...    -1        0   unknown
2       33  entrepreneur   married  ...    -1        0   unknown
3       47   blue-collar   married  ...    -1        0   unknown
4       33       unknown    single  ...    -1        0   unknown
...    ...           ...       ...  ...   ...      ...       ...
45206   51    technician   married  ...    -1        0   unknown
45207   71       retired  divorced  ...    -1        0   unknown
45208   72       retired   married  ...   184        3   success
45209   57   blue-collar   married  ...    -1        0   unknown
45210   37  entrepreneur   married  ...   188       11     other

[45211 rows x 16 columns]

In [32]:
y

y
0       no
1       no
2       no
3       no
4       no
...    ...
45206  yes
45207  yes
45208  yes
45209   no
45210   no

[45211 rows x 1 columns]

In [4]:
y_labelencoder = LabelEncoder()
y = np.reshape(y, (-1, 1))
y=np.ravel(y)
Y = y_labelencoder.fit_transform(df['y'])
Y

array([0, 0, 0, ..., 1, 0, 0])

In [6]:
Y = Y.reshape(-1, 1)
Y = np.ravel(Y)
X = pd.get_dummies(x, drop_first=False)
X

age  balance  day  ...  poutcome_other  poutcome_success  poutcome_unknown
0       58     2143    5  ...               0                 0                 1
1       44       29    5  ...               0                 0                 1
2       33        2    5  ...               0                 0                 1
3       47     1506    5  ...               0                 0                 1
4       33        1    5  ...               0                 0                 1
...    ...      ...  ...  ...             ...               ...               ...
45206   51      825   17  ...               0                 0                 1
45207   71     1729   17  ...               0                 0                 1
45208   72     5715   17  ...               0                 1                 0
45209   57      668   17  ...               0                 0                 1
45210   37     2971   17  ...               1                 0                 0

[45211 rows x 51 columns]

In [10]:
train_x, test_x, train_y, test_y = train_test_split(X, Y, test_size=.2)

In [11]:
train_x = train_x[train_x.columns[0:-1]].values
train_x

array([[  60, 1608,   11, ...,    0,    0,    0],
       [  55, 1373,    9, ...,    0,    0,    0],
       [  44, 1379,   30, ...,    0,    0,    0],
       ...,
       [  51, 3942,   17, ...,    0,    0,    0],
       [  27,  -67,    6, ...,    1,    0,    0],
       [  31,    9,    7, ...,    0,    0,    0]])

In [12]:
test_x = test_x[test_x.columns[0:-1]].values
test_x

array([[   46,   926,    19, ...,     0,     1,     0],
       [   56,  3616,    12, ...,     0,     0,     0],
       [   60, 13360,     5, ...,     0,     0,     0],
       ...,
       [   38,  1333,    28, ...,     0,     0,     0],
       [   24,    61,     7, ...,     0,     1,     0],
       [   38,  5779,    23, ...,     0,     0,     0]])

Running built in Perceptron Algorithm

In [14]:
from sklearn.linear_model import Perceptron
fun=Perceptron()

fun.fit(train_x, train_y)
y_pred = fun.predict(test_x)
# test_x
accuracy_score(test_y, y_pred)

0.8226252349883888

In [15]:
y_train_pred=fun.predict(train_x)
accuracy_score(train_y, y_train_pred)

0.8287989382879893

using my own Algorithm

In [16]:
per=PerceptronAlgorithm()

per.fit(train_x, train_y)
y_pred = per.predict(test_x)
accuracy_score(test_y, y_pred)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: RuntimeWarning: invalid value encountered in multiply
  app.launch_new_instance()


0.8816764348114564

In [17]:
y_train_pred=per.predict(train_x)
accuracy_score(train_y, y_train_pred)

0.8833499225834992

**Logistic regression Algorithm**

Creating Logistic Regression Algorithm using Gradient Descent

In [18]:
import numpy as np


class LogisticRegressionAlgorithm:
    def __init__(self, learning_rate=0.01, iterations=1000):

        self.lr = learning_rate
        self.n = iterations
        self.weights = None
        self.bias = None

    def fit(self, X, Y):

        self.weights = np.zeros(X.shape[1])
        self.bias = 0

        for epoch in range(self.n):
          model=np.dot(X,self.weights)+self.bias
          y_pred= self._sigmoid(model)

          dw=(1/X.shape[0])*np.dot(X.T,(y_pred-Y))   
          db=(1/X.shape[0])* np.sum(y_pred-Y)  

          self.weights-=self.lr*dw
          self.bias-=self.lr*db    

    def predict(self, X):

        model=np.dot(X,self.weights)+self.bias
        y_pred= self._sigmoid(model)
        y_pred_ans=[1 if i>0.5 else 0 for i in y_pred]
        return y_pred_ans

       

    def _sigmoid(self, z):
        return 1/(1+np.exp(-z))

Using the same dataset as used in perceptron Algorithm

Using Built in Logistic regression  classifier

In [23]:
from sklearn.linear_model import LogisticRegression
fun=LogisticRegression()
fun.fit(train_x, train_y)
y_pred2 = fun.predict(test_x)
accuracy_score(test_y, y_pred2)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.8865420767444432

In [24]:
y_train_pred2=fun.predict(train_x)
accuracy_score(train_y, y_train_pred2)

0.8882437513824375

Using my own Algorithm


In [26]:
log=LogisticRegressionAlgorithm()

log.fit(train_x, train_y)
y_pred22 = log.predict(test_x)
accuracy_score(test_y, y_pred22)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:37: RuntimeWarning: overflow encountered in exp


0.8552471524936415

In [27]:
y_train_pred22=per.predict(train_x)
accuracy_score(train_y, y_train_pred22)

0.8833499225834992

**LP solver(scipy.optimize.linprog)**

In [44]:
import numpy as np


class LPsolver:
    def __init__(self, learning_rate=0.01, n_iterations=100):

        self.weights = None

    def fit(self, X, Y):
        
        self.bias = 0
        U=np.zeros(X.shape[1])
        np.append(U,1)
        V=np.ones(X.shape[0])
        A=[]
        for i in range(X.shape[0]):
          Z=[]
          for j in range(X.shape[1]):
            a=Y[i]*X[i][j]
            Z.append(a)
          A.append(Z)
        A=np.array(A)
        from scipy.optimize import linprog
        ans = linprog(c=U,A_ub=A,b_ub=V)
        self.weights=ans.success
        
        

    def predict(self, X):
        y_pred=[]
        X = np.hstack((X, np.ones((X.shape[0], 1), dtype=X.dtype)))
        y= np.dot(X,self.weights)
        for val in range(X.shape[0]):
          y_pred.append(self.helper(y[val][0]))
        return y_pred

       
    def helper(self, val):
        if (val <= 0):
            return 1
        return 0

In [45]:
lp=LPsolver()

lp.fit(train_x, train_y)
y_pred=lp.predict(test_x)

accuracy_score(test_y, y_pred)

/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


0.8816764348114564

In [46]:
y_pred_train=lp.predict(test_x)

accuracy_score(test_y, y_pred_train)

0.8816764348114564